<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Actividades</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>


<div id="main">

    <section class="cp-blog padding-top-60">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="cp-post-box">
                        <div class="frame">
                            <a href="#"><img src="/front/src/images/sections/actii1.jpg" alt="elecciones en mexico"></a>
                        </div>
                        <div class="cp-text-box">
                            <h2>¿Qué hace el <span>IIDE</span>?</h2>

                            <p>El Instituto busca desarrollar los siguientes objetivos y actividades particulares:</p>

                            <div class="accordions-row">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-9">
                                            <div class="cp-accordions">
                                                <h3>Con el fin de lograr los citados objetivos, el Instituto puede participar en el
                                                    siguiente tipo de actividades:</h3>

                                                <div class="accordion-style-1">
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section9">Desarrollar redes<span><i
                                                                    class="fa fa-minus"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Desarrollar redes en México y en todo el
                                                                    mundo en la esfera de los procesos
                                                                    electorales.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section10">Establecer<span><i
                                                                    class="fa fa-chevron-right"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Establecer y mantener servicios de
                                                                    información.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section11">Proporcionar asesoría<span><i
                                                                    class="fa fa-chevron-right"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Proporcionar asesoría, orientación y
                                                                    apoyo sobre la función del gobierno y de
                                                                    la oposición, los partidos políticos, las
                                                                    reformas electorales y el rol del poder
                                                                    legislativo en dicha encomienda, los
                                                                    organismos electorales, un poder judicial
                                                                    independiente, los medios de comunicación y
                                                                    demás aspectos del proceso electoral en un
                                                                    contexto democrático pluralista. </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section12">Establecer convenios de colaboración<span><i
                                                                    class="fa fa-chevron-right"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Establecer convenios de colaboración
                                                                    con los órganos del poder público,
                                                                    organismos electorales, universidades, entre otros organismos, en actividades
                                                                    relacionadas con el marco de sus funciones y
                                                                    los procesos democráticos.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section13">Alentar la investigación y la difusión<span><i
                                                                    class="fa fa-chevron-right"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Alentar la investigación y la difusión y
                                                                    aplicación de los hallazgos de la
                                                                    investigación dentro de la esfera de
                                                                    competencia del Instituto.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section13">Organizar y participar en seminarios<span><i
                                                                    class="fa fa-chevron-right"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Organizar y participar en seminarios,
                                                                    talleres y capacitación sobre elecciones
                                                                    libres y justas en el contexto de sistemas
                                                                    democráticos pluralistas.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="cp_aaccordion-row">
                                                        <div class="accordion_cp" id="section13">Participar en otras actividades<span><i
                                                                    class="fa fa-chevron-right"></i></span></div>
                                                        <div class="contain_cp_accor">
                                                            <div class="content_cp_accor">
                                                                <p>Participar en otras actividades
                                                                    relacionadas con elecciones y democracia
                                                                    conforme surja la necesidad.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="cp-share-post-row"><strong class="title">Compartir información:</strong>
                                <ul>
                                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <aside>
                        <div class="cp-sidebar">
                            <div class="cp-sidebar-box">
                                <h3>Áreas de conocimiento</h3>

                                <div class="cp-practice-area">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-home"></i>Partidos Politicos</a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-bank"></i>Estado de la Democracia</a></li>
                                        <li><a href="#"><i class="fa fa-building-o"></i>Construcción Constitucional</a></li>
                                        <li><a href="#"><i class="fa fa-money"></i>Financiamiento
                                                Político</a></li>
                                        <li><a href="#"><i class="fa fa-car"></i>Democracia y Conflicto</a></li>
                                        <li><a href="#"><i class="fa fa-male"></i>Procesos Electorales</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </section>

</div>
