<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Contáctanos</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>
<div id="main">
    <section class="cp-contact-style-1 padding-tb-60">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="left-box">
                        <h3>Rellene el siguiente formulario para contactarnos</h3>
                        <form action="" method="post" id="contact-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <input type="text" name="name" placeholder="Nombre *">
                                </div>
                                <div class="col-md-6">
                                    <input type="text" name="phone" placeholder="Telefono *">
                                </div>
                                <div class="col-md-6">
                                    <input type="text" name="email" placeholder="Email *">
                                </div>
                                <div class="col-md-6">
                                    <input type="text" name="department" placeholder="Asunto *" >
                                </div>
                                <div class="col-md-12">
                                        <textarea name="msg" cols="10" rows="10" placeholder="Mensaje *" ></textarea>
                                </div>
                                <div class="col-md-12">
                                    <input type="submit" class="submit btn-submit" value="Enviar">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal fade in" id="background-contact" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="content-fa">
                            <h5 class="message-background" id="wm">Enviando Mensaje, espere un momento por favor.....</h5>
                            <h5 class="message-background hide" id="sc">Su mensaje se ha enviado, contactaremos con usted los mas pronto posible, Gracias.</h5>
                            <h5 class="message-background hide" id="error-contact">Lo sentimos, ha ocurrido un error intente mas tarde.</h5>
                            <h1><i class="fa fa-circle-o-notch fa-spin style-fa"></i></h1>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="right-box">
                        <h3>Información de contacto</h3>
                        <address>
                            <ul>
                                <!--li><i class="fa fa-home"></i> <b> Sede en Bahia Magdalena 42, colonia Verónica Anzures, Delegación Miguel Hidalgo, código postal 11300, Ciudad de México.</b></li-->
                                <li><i class="fa fa-phone"></i>55 60 62 77 22</li>
                                <li><i class="fa fa-envelope-o"></i><a href="mailto:">Email: <span>contactanos@iide.com.mx</span></a></li>
                                <li><i class="fa fa-globe"></i><a href="#">www.iide.com.mx/</a></li>
                            </ul>
                        </address>
                    </div>
                </div>
            </div>
        </div>
        <div class="cp-map-row">
            <div id="map_contact_2" class="map_canvas active"></div>
        </div>
    </section>
</div>