<div class="container">
	<div class="content main-navigation">
		<div class="row">
			<div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
				<ul id="parallelogram">
				</ul>
			</div>
			<div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
				<p class="titleview">Directorio</p>
			</div>
			<div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
				<ul id="parallelogram2">
				</ul>
			</div>
		</div>
	</div>
</div>
<section class="cp-blog padding-top-60">
	<div class="container">
		<div class="row">
			<div class="col-md-12 direc">
				<div class="cp-award-section">
					<div class="cp-award-box">
						<div class="icon-box"><i class="fa fa-trophy"></i></div>
						<div class="text-box">
							<h3><a class="name-directory" href="#">Mtro. Oswald Lara Borges <br/> Director General</a></h3>
						</div>
						<div class="logo-box"><a href="#"><img src="/front/src/images/attorneys/oswald-directorio.jpg" alt="oswald lara borgues"></a></div>
					</div>
					<div class="cp-award-box">
						<div class="icon-box"><i class="fa fa-legal"></i></div>
						<div class="text-box">
							<h3><a class="name-directory" href="#">Lic. Juan Omar Rubio Espinosa <br/>  Director de Enlace Institucional</a></h3>
						</div>
						<div class="logo-box"><a href="#"><img src="/front/src/images/attorneys/director.jpg" alt="oswald lara borgues"></a></div>
					</div>
					<div class="cp-award-box">
						<div class="icon-box"><i class="fa fa-thumbs-o-up"></i></div>
						<div class="text-box">
							<h3><a class="name-directory" href="#">Lic. Lazaro Torruco Guzmán <br/>  Sub Director Administrativo</a></h3>
						</div>
						<div class="logo-box"><a href="#"><img src="/front/src/images/attorneys/lazaro2.jpg" alt="oswald lara borgues"></a></div>
					</div>
					<div class="cp-award-box">
						<div class="icon-box"><i class="fa fa-bank"></i></div>
						<div class="text-box">
							<h3><a class="name-directory" href="#"><br>Administrativo</a></h3>
						</div>
						<div class="logo-box"><a href="#"><img src="/front/src/images/siluetadirectorio.png" alt="oswald lara borgues"></a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>