<style>
    .fb_iframe_widget iframe{
        height: 51vh !important;
    }
    iframe {
        width: 60vw !important;
    }
</style>
<div class="block">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Iberonautas</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>
    </div>
</div>
<section class="cp-gallery padding-tb-60 gallery">
    <div class="container">
        <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bhoechie-tab-container">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bhoechie-tab-menu">
                    <div class="list-group">
                        <a href="#" class="list-group-item active text-center">
                            <h4 class="fa fa-facebook" aria-hidden="true"></h4><br/>FACEBOOK
                        </a>
                        <a href="#" class="list-group-item text-center">
                            <h4 class="fa fa-twitter" aria-hidden="true"></h4><br/>TWITTER
                        </a>
                        <a href="#" class="list-group-item text-center">
                            <h4 class="fa fa-youtube" aria-hidden="true"></h4><br/>YOUTUBE
                        </a>
                        <a href="#" class="list-group-item text-center">
                            <h4 class="glyphicon glyphicon-bullhorn"></h4><br/>IIDEACTUANDO
                        </a>
                        <a href="#" class="list-group-item text-center">
                            <h4 class="fa fa-picture-o" aria-hidden="true"></h4><br/>GALERÍA
                        </a>
                    </div>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 bhoechie-tab iberonautas">
                    <div class="bhoechie-tab-content active facebook">
                        <!--h3 class="titleRedesIberonautas">Facebook</h3-->
                        <div class="cp-box">
                            <div class="fb-page ibero" data-href="https://www.facebook.com/IIDEMEXICO1/" data-tabs="timeline" data-width="500" data-height="500" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false"><blockquote cite="https://www.facebook.com/IIDEMEXICO1/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/IIDEMEXICO1/">Instituto Iberoamericano de Derecho Electoral</a></blockquote></div>
                        </div>
                    </div>
                    <div class="bhoechie-tab-content twitter">
                         <!--h3 class="titleRedesIberonautas">Twitter</h3-->
                        <a class="twitter-timeline"  href="https://twitter.com/IIDE_MEXICO" data-widget-id="281910885067399169">Tweets por el @IIDE_MEXICO.</a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

                    </div>

                    <div class="bhoechie-tab-content">
                        <!--h3 class="titleRedesIberonautas">Youtube</h3-->
                        <iframe class="youtube" width="550" height="450" src="https://www.youtube.com/embed/j44iIL8rrYg" frameborder="0" allowfullscreen></iframe>
                    </div>
                    <div class="bhoechie-tab-content">
                        <!--h3 class="titleRedesIberonautas">IIDEACTUANDO</h3-->
                        <div id="disqus_thread"></div>
                        <script>
                            (function() { // DON'T EDIT BELOW THIS LINE
                                var d = document, s = d.createElement('script');
                                s.src = '//http-iide-com-mx.disqus.com/embed.js';
                                s.setAttribute('data-timestamp', +new Date());
                                (d.head || d.body).appendChild(s);
                            })();
                        </script>
                        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                    </div>
                    <div class="bhoechie-tab-content">
                        <!--h3 class="titleRedesIberonautas">Galería</h3-->
                        <div id="myCarousel5" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel5" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel5" data-slide-to="1"></li>
                                <li data-target="#myCarousel5" data-slide-to="2"></li>
                                <li data-target="#myCarousel5" data-slide-to="3"></li>
                                <li data-target="#myCarousel5" data-slide-to="4"></li>
                                <li data-target="#myCarousel5" data-slide-to="5"></li>
                                <li data-target="#myCarousel5" data-slide-to="6"></li>
                                <li data-target="#myCarousel5" data-slide-to="7"></li>
                                <li data-target="#myCarousel5" data-slide-to="8"></li>
                            </ol>
                            <div class="carousel-inner iberonautas">
                                <div class="item active">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 1.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 2.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 3.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 4.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 5.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 6.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 7.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 8.jpg">
                                </div>
                                <div class="item">
                                    <img class="imgiberonautas" src="/front/src/images/iberonauta/foto 9.jpg">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>