<div id="block-drupalnav-drupalnav" class="block block-drupalnav hidden-xs">
    <div class="content main-navigation">
        <div class="row">
            <ul id="parallelogram2">
            </ul>
            <ul id="parallelogram">
            </ul>
        </div>
        <ul class="menu rojo">
            <li class="first expanded">
				<span class="active main">
					<p class="letraMenu oples">ORGANISMOS PÚBLICOS <br> LOCALES ELECTORALES</p>
				</span>
            </li>
        </ul>
    </div>
</div>


<div id="main">

    <section class="cp-gallery padding-tb-60">
        <div class="container">
            <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-1.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieeags.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">AGUASCALIENTES</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-2.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieebc.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">BAJA CALIFORNIA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-4.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieebcs.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">BAJA CALIFORNIA SUR</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-3.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieec.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">CAMPECHE</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-5.jpg" alt="img">
                                <div class="caption"><a href="http://www.iepc-chiapas.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">CHIAPAS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-6.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieechihuahua.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">CHIHUAHUA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-7.jpg" alt="img">
                                <div class="caption"><a href="http://www.iec.org.mx/v1/index.php" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">COAHUILA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-8.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieecolima.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">COLIMA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-9.jpg" alt="img">
                                <div class="caption"><a href="http://www.iedf.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">D.F.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-10.jpg" alt="img">
                                <div class="caption"><a href="http://www.iepcdgo.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">DURANGO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-11.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieeg.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">GUANAJUATO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-12.jpg" alt="img">
                                <div class="caption"><a href="http://www.iepcgro.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">GUERRERO</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-13.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieehidalgo.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">HIDALGO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-14.jpg" alt="img">
                                <div class="caption"><a href="http://www.iepcjalisco.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">JALISCO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-15.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieem.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">MÉXICO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-16.jpg" alt="img">
                                <div class="caption"><a href="http://www.iem.org.mx/index.php" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">MICHOACÁN</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-17.jpg" alt="img">
                                <div class="caption"><a href="http://impepac.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">MORELOS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-18.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieenayarit.org/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">NAYARIT</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-19.jpg" alt="img">
                                <div class="caption"><a href="http://www.cee-nl.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">NUEVO LEÓN</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-20.jpg" alt="img">
                                <div class="caption"><a href="http://ieepco.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">OAXACA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-21.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieepuebla.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">PUEBLA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-22.jpg" alt="img">
                                <div class="caption"><a href="http://ieeq.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">QUERÉTARO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-23.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieqroo.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">QUINTANA ROO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-24.jpg" alt="img">
                                <div class="caption"><a href="http://www.ceepacslp.org.mx" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">SAN LUIS POTOSI</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-25.jpg" alt="img">
                                <div class="caption"><a href="http://www.cee-sinaloa.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">SINALOA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-26.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieesonora.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">SONORA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-27.jpg" alt="img">
                                <div class="caption"><a href="http://www.iepct.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">TABASCO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-28.jpg" alt="img">
                                <div class="caption"><a href="http://ietam.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">TAMAULIPAS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-29.jpg" alt="img">
                                <div class="caption"><a href="http://www.itetlax.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">TLAXCALA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-30.jpg" alt="img">
                                <div class="caption"><a href="https://oplever.org.mx/index.html" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">VERACRUZ</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-31.jpg" alt="img">
                                <div class="caption"><a href="http://www.iepac.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">YUCATÁN</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/gallery-medium-img-32.jpg" alt="img">
                                <div class="caption"><a href="http://www.ieez.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">ZACATECAS</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>