<div class="block">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Quiénes somos</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>
<section class="cp-blog padding-top-60 about">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 bhoechie-tab-container about">
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 bhoechie-tab-menu">
                    <div class="list-group">
                        <a href="#" class="--menuItem list-group-item active text-center about">
                            <h4 class="glyphicon glyphicon-bookmark"></h4>¿Qué es el IIDE?
                        </a>
                        <a href="#" class="--menuItem list-group-item text-center about">
                            <h4 class="glyphicon glyphicon-search"></h4>Objetivos del IIDE
                        </a>
                        <a href="#" class="--menuItem list-group-item text-center about">
                            <h4 class="glyphicon glyphicon-star"></h4>Fines del IIDE
                        </a>
                        <a href="#" class="list-group-item text-center about">
                        </a>
                        <a href="#" class="list-group-item text-center about">
                        </a>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 bhoechie-tab" id="myTababout">
                    <div class="bhoechie-tab-content active">
                        <div class="cp-post-box container">
                            <div class="frame quienes">
                                <a href="#"><img class="quees" src="/front/src/images/sections/Bann1.jpg" alt="img"></a>
                            </div>
                            <div class="cp-text-box">
                                <h3 class="black"><span>Instituto</span> Iberoamericano <span>de Derecho Electoral</span></h3>
                                <br>
                                <p class="text-justify">Es una institución que trabaja en la investigación, difusión y capacitación sobre asuntos relacionados con los temas electorales y de la calidad democrática, integrada por un grupo interdisciplinario de profesionistas con el fin de promover mejores herramientas y conocimientos sobre las elecciones y la calidad democrática.</p>
                                <p class="text-justify">Las elecciones son la pieza clave del entramado institucional democrático y la calidad democrática se define por este Instituto, como la consecuencia de las acciones y decisiones para mejorar las condiciones de vida de los ciudadanos por parte de las instituciones políticas, jurídicas, económicas y sociales a través de diversas dimensiones en los diversos ámbitos de gobierno con un especial énfasis en el buen gobierno, transparencia e igualdad.</p>
                            </div>
                        </div>
                    </div>
                    <div class="bhoechie-tab-content">
                        <div class="cp-post-box container">
                            <div class="frame quienes">
                                <a href="#"><img class="objetivos" src="/front/src/images/sections/foto2.jpg" alt="img"></a>
                            </div>
                            <div class="cp-text-box objetivos">
                                <h3 class="black">Los objetivos del Instituto son:</h3>
                                <div class="accordions-row">
                                    <div class="col-md-12">
                                        <div class="cp-accordions">

                                            <div class="accordion-style-1">
                                                <div class="cp_aaccordion-row">
                                                    <div class="accordion_cp" id="section9">Promover y fomentar el conocimiento<span><i
                                                                class="fa fa-minus"></i></span></div>
                                                    <div class="contain_cp_accor">
                                                        <div class="content_cp_accor">
                                                            <p class="text-justify">Promover y fomentar el conocimiento y
                                                                difusión de los temas relacionados a las
                                                                elecciones y la calidad democrática tanto
                                                                en México como en otras partes del mundo;</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="cp_aaccordion-row">
                                                    <div class="accordion_cp" id="section10">Apoyar<span><i
                                                                class="fa fa-chevron-right"></i></span></div>
                                                    <div class="contain_cp_accor">
                                                        <div class="content_cp_accor">
                                                            <p class="text-justify">Apoyar para mejorar los procesos
                                                                electorales democráticos.</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="cp_aaccordion-row">
                                                    <div class="accordion_cp" id="section11">Ampliar el conocimiento<span><i
                                                                class="fa fa-chevron-right"></i></span></div>
                                                    <div class="contain_cp_accor">
                                                        <div class="content_cp_accor">
                                                            <p class="text-justify">Ampliar el conocimiento y promover la
                                                                ejecución y difusión de las normas,
                                                                reglas y lineamientos que se aplican al
                                                                pluralismo multipartidista y los procesos
                                                                democráticos. </p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="cp_aaccordion-row">
                                                    <div class="accordion_cp" id="section12">Incrementar el conocimiento<span><i
                                                                class="fa fa-chevron-right"></i></span></div>
                                                    <div class="contain_cp_accor">
                                                        <div class="content_cp_accor">
                                                            <p class="text-justify">Incrementar el conocimiento y mejorar el
                                                                aprendizaje sobre los procesos
                                                                electorales democráticos. </p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="cp_aaccordion-row">
                                                    <div class="accordion_cp" id="section13">Promover la transparencia<span><i
                                                                class="fa fa-chevron-right"></i></span></div>
                                                    <div class="contain_cp_accor">
                                                        <div class="content_cp_accor">
                                                            <p class="text-justify">Promover la transparencia, la rendición
                                                                de cuentas, el profesionalismo y la eficiencia
                                                                en el proceso electoral, en el contexto del
                                                                desarrollo democrático.</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bhoechie-tab-content">
                        <div class="cp-post-box container">
                            <div class="frame quienes">
                                <a href="#"><img class="fines" src="/front/src/images/sections/foto3.jpg" alt="img"></a>
                            </div>
                            <div class="cp-text-box objetivos">
                                <h3 class="black">Los fines del instituto son:</h3>
                                <div class="cp-heading-1">
                                    <em  class="text-justify">El Instituto trabaja desarrollando y cooperando en
                                        diversos proyectos con instituciones nacionales e
                                        internacionales, académicas, sociales y políticas en
                                        México y en varias partes del mundo para el
                                        desarrollo en las áreas de elecciones y de la calidad
                                        democrática.
                                    </em>
                                    <em  class="text-justify">El Instituto tiene un funcionamiento basado en la
                                        ética, transparencia y profesionalismo en sus
                                        tareas. Además, de buscar ser una herramienta que
                                        sirva como apoyo a la sociedad en la mejora de los
                                        procesos electorales y de la calidad de la
                                        democracia, la participación política equitativa, la
                                        representación de mujeres y hombres en la política y
                                        en la toma de decisiones para ayudar a impulsar la
                                        voluntad política necesaria para el cambio.
                                    </em>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bhoechie-tab-content">
                        <div class="cp-post-box">
                            <div class="cp-text-box objetivos">

                            </div>
                        </div>
                    </div>
                    <div class="bhoechie-tab-content">
                        <div class="cp-post-box">
                            <div class="cp-text-box objetivos">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-lg-3 col-sm-3 col-xs-12">
                <aside>
                    <div class="cp-sidebar">
                        <div class="cp-sidebar-box">
                            <h3 class="black">Áreas de conocimiento</h3>
                            <div class="cp-practice-area">
                                <ul>
                                    <?php foreach($areas as $are):?>
                                    <li><a href="#"><i class="fa <?=$are->icon;?>"></i><?=$are->name;?></a>
                                    </li>
                                    <?php endforeach?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>