<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Revista IIDE</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>
<div id="main">
    <section class="cp-blog padding-top-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bhoechie-tab-container">
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 bhoechie-tab-menu">
                        <div class="list-group">
                            <a href="#" class="list-group-item active text-center view magazine">
                                <h4 class="glyphicon glyphicon-book"></h4><br/>Revista
                            </a>
                            <a href="#" class="list-group-item text-center view magazine">
                                <h4 class="glyphicon glyphicon-book"></h4><br/>Sobre la revista
                            </a>
                            <a href="#" class="list-group-item text-center view magazine">
                                <h4 class="glyphicon glyphicon-tasks"></h4><br/>Ultimas publicaciones
                            </a>

                            <a href="#" class="list-group-item text-center view magazine">
                                <h4 class="glyphicon glyphicon-question-sign"></h4><br/>Criterios editoriales
                            </a>
                            <a href="#" class="list-group-item text-center view magazine">
                                <h4 class="glyphicon glyphicon-king"></h4><br/>Consejo editorial
                            </a>

                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 bhoechie-tab"   id="myTabMagazine">
                        <div class="bhoechie-tab-content active">
                            <div class="magazine">
                                <a href="/ver-revista-digital">
                                    <img class="magazineimg" src="/front/src/images/magazine.jpg">
                                </a>
                            </div>
                        </div>
                        <div class="bhoechie-tab-content">
                            <p class="text-justify">La Revista IIDE es una revista del Instituto Iberoamericano de Derecho Electoral la cual se publicara semestralmente.</p>
                        </div>
                        <div class="bhoechie-tab-content">
                            <p class="text-justify">
                                Ultimos Números......
                            </p>
                        </div>
                        <div class="bhoechie-tab-content" style="overflow-y:auto;">
                            <h4 class="black">NORMAS PARA LA PRESENTACIÓN</h4>
                            <p class="text-justify text-general">Monográfica. La presentación de los artículos serán análisis de un tema vinculado con el área jurídica y política.</p><br>
                            <p class="text-justify text-general">Artículos. Se incluyen trabajos relevantes dedicados a varios temas jurídicos y políticos.</p><br>
                            <p class="text-justify text-general">Análisis jurisprudencial. Artículos de estudios de casos relevantes que los órganos electorales han conocido.</p>
                            <h4 class="black">CRITERIOS EDITORIALES PARA LA PRESENTACIÓN DE COLABORACIONES</h4>
                            <p>
                            <ul>
                                <li class="text-justify magazine">Se publicarán artículos originales e inéditos. La revista tendrá como idioma oficial el español.</li>
                                <li class="text-justify magazine">Los artículos deberán enviarse al correo electrónico oficial de la Revista el cual es revistaiide@iide.com.mx, acompañado del archivo adjunto, indicando el nombre del autor y el título del artículo.</li>
                                <li class="text-justify magazine">Los artículos deben ser enviados en el formato de hoja tamaño carta que deberá tener márgenes de 3 centímetros, en el procesador de textos Word, con interlineado de normal y letra Times New Roman de 12 puntos justificada y numeración de las hojas en la parte inferior.</li>
                                <li class="text-justify magazine">El articulo preferentemente debe ser de veinticinco a treinta cuartillas. No se devuelven los originales recibidos para su publicación.</li>
                                <li class="text-justify magazine">Cada trabajo deberá ir acompañado de lo siguiente: 1) resumen de 80 a 100 palabras; 2) cinco palabras claves, que identifiquen el contenido del artículo; y c) sumario.</li>
                                <li class="text-justify magazine">En la elaboración de notas a pie de página se sugiere utilizar la siguiente presentación:</li>
                                <img src="/front/src/images/criterios.png" alt="">
                            </ul>
                            </p>
                            <br>
                            <p  class="black text-justify">Las palabras en otro idioma deberán ir en itálicas o cursivas. De igual manera deberán usarse cursivas para destacar alguna palabra (no usar mayúsculas). Los cuadros, esquemas, diagramas, tablas y gráficas deberán ir colocada en el lugar exacto que les corresponde. Si es necesario incluir notas en alguno de estos elementos, deberán señalarse con asterisco.</p>
                            <br>
                            <p>
                            <ul>
                                <li class="text-justify magazine">Todo trabajo deberá contener nombre completo, la institución donde labora, cargo académico, teléfono, correo electrónico y redes sociales.</li>
                                <li class="text-justify magazine">Todo material que cumpla con las normas y criterios será sometido a dictamen doble ciego, aceptado el artículo, el autor deberá ceder el derecho de autor a la Revista del IIDE.</li>
                            </ul>
                            </p>
                        </div>
                        <div class="bhoechie-tab-content">
                            <div class="consejo">
                                <ul class="consejo">
                                    <li class="black">Mtro. Oswald Lara Borges</li>
                                    <li class="black">Lic. Jesús Raciel García Ramírez</li>
                                    <li class="black">Mtra. Nuria Gabriela Hernández Abarca</li>
                                    <li class="black">Mtro. Miguel Ángel Vera Martínez</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>