<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Sistema Electoral Iberoamericano</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>
<div id="main">
    <section class="cp-gallery padding-tb-60 gallery">
        <div class="container">
            <ul class="row">
                <li class="col-md-9">
                    <div id="vmap" style="width: 100%; height: 550px;"></div>
                    <h5>*Da clic en un pais iberoamericano para ver sus leyes</h5>
                </li>

                <li class="col-md-3">
                    <div id="content-lote-element" class="hidden" style="max-height:550px; overflow-y:auto; width: 100%;">
                        <h2 class="cl-manzana" data-value=""></h2>
                        <h3 class="cl-manzana" data-value=""></h3>
                        <div class="accordion-style-1">
                            <div class="cp_aaccordion-row">
                                <div class="accordion_cp" id="section9">Constitución<span><i
                                            class="fa fa-minus"></i></span></div>
                                <div class="contain_cp_accor">
                                    <div class="content_cp_accor">
                                        <ul>
                                            <li id="constitucion"></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="cp_aaccordion-row">
                                <div class="accordion_cp" id="section10">Leyes Electorales<span><i
                                            class="fa fa-chevron-right"></i></span></div>
                                <div class="contain_cp_accor">
                                    <div class="content_cp_accor">
                                        <ul>
                                            <li class="leyes"></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="cp_aaccordion-row">
                                <div class="accordion_cp" id="section11">Jurisprudencia<span><i
                                            class="fa fa-chevron-right"></i></span></div>
                                <div class="contain_cp_accor">
                                    <div class="content_cp_accor">
                                        <ul>
                                            <li class="jurisprudencia"></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </section>
</div>
<script>



    jqvmap-label
</script>