<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Tribunales Locales</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>
<div id="main">
    <section class="cp-gallery padding-tb-60">
        <div class="container">
            <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-2.jpg" alt="img">
                                <div class="caption"><a href="http://www.poderjudicialags.gob.mx/salaae/sae.html" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">AGUASCALIENTES</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-1.jpg" alt="img">
                                <div class="caption"><a href="http://tje-bc.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">BAJA CALIFORNIA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-3.jpg" alt="img">
                                <div class="caption"><a href="http://teebcs.org/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">BAJA CALIFORNIA SUR</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-4.jpg" alt="img">
                                <div class="caption"><a href="http://www.teec.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">CAMPECHE</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-5.jpg" alt="img">
                                <div class="caption"><a href="http://www.tribunalelectoralchiapas.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">CHIAPAS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-6.jpg" alt="img">
                                <div class="caption"><a href="http://techihuahua.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">CHIHUAHUA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-7.jpg" alt="img">
                                <div class="caption"><a href="http://www.pjec.gob.mx/tribunal-electoral.html" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">COAHUILA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-8.jpg" alt="img">
                                <div class="caption"><a href="http://www.tee.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">COLIMA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-9.jpg" alt="img">
                                <div class="caption"><a href="http://www.tedf.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">D.F.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-10.jpg" alt="img">
                                <div class="caption"><a href="http://tedgo.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">DURANGO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-11.jpg" alt="img">
                                <div class="caption"><a href="http://www.teegto.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">GUANAJUATO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-12.jpg" alt="img">
                                <div class="caption"><a href="http://teegro.gob.mx/inicio/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">GUERRERO</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-13.jpg" alt="img">
                                <div class="caption"><a href="http://www.trielectoralhidalgo.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">HIDALGO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-14.jpg" alt="img">
                                <div class="caption"><a href="http://www.triejal.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">JALISCO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-15.jpg" alt="img">
                                <div class="caption"><a href="http://www.teemmx.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">MÉXICO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-16.jpg" alt="img">
                                <div class="caption"><a href="http://www.teemich.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">MICHOACÁN</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-17.jpg" alt="img">
                                <div class="caption"><a href="http://www.teem.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">MORELOS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-18.jpg" alt="img">
                                <div class="caption"><a href="" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">NAYARIT</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-19.jpg" alt="img">
                                <div class="caption"><a href="http://www.tee-nl.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">NUEVO LEÓN</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-20.jpg" alt="img">
                                <div class="caption"><a href="http://teoax.org/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">OAXACA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-21.jpg" alt="img">
                                <div class="caption"><a href="http://www.teep.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">PUEBLA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-22.jpg" alt="img">
                                <div class="caption"><a href="http://www.teeq.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">QUERÉTARO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-23.jpg" alt="img">
                                <div class="caption"><a href="http://www.teqroo.com.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">QUINTANA ROO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-24.jpg" alt="img">
                                <div class="caption"><a href="http://teeslp.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">SAN LUIS POTOSI</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-25.jpg" alt="img">
                                <div class="caption"><a href="http://www.teesin.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">SINALOA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-26.jpg" alt="img">
                                <div class="caption"><a href="http://www.teesonora.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">SONORA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-27.jpg" alt="img">
                                <div class="caption"><a href="http://www.tet.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">TABASCO</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-28.jpg" alt="img">
                                <div class="caption"><a href="http://www.trieltam.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">TAMAULIPAS</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-29.jpg" alt="img">
                                <div class="caption"><a href="http://www.tetlax.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">TLAXCALA</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-30.jpg" alt="img">
                                <div class="caption"><a href="http://www.teever.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">VERACRUZ</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-31.jpg" alt="img">
                                <div class="caption"><a href="http://www.teey.org.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">YUCATÁN</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                    <div class="item">
                        <div class="cp-box">
                            <div class="frame oples"> <img src="/front/src/images/gallery/gallery-medium/tribunal-img-32.jpg" alt="img">
                                <div class="caption"><a href="http://www.teez.gob.mx/" class="zoom" target="_blank"><i class="fa fa-search-plus"></i></a></div>
                                <p class="oples-title">ZACATECAS</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>