<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram">
                </ul>
            </div>
            <div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
                <p class="titleview">Revista IIDE</p>
            </div>
            <div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
                <ul id="parallelogram2">
                </ul>
            </div>
        </div>

    </div>
</div>
<div id="main">
    <section class="cp-blog padding-top-60 viewmagazine">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div style="width: 100%" class="container" id="full-screen">
                    <div id="canvas">
                        <div  class="magazine-viewport" style="">
                            <div class="container">
                                <div class="magazine" id="magazine-scroll">
                                    <div ignore="1" class="next-button"></div>
                                    <div ignore="1" class="previous-button"></div>
                                </div>
                            </div>
                            <div class="bottom">
                                <div id="slider-bar" class="turnjs-slider">
                                    <div id="slider"></div>
                                </div>
                            </div>
                        </div>
                        <button href="#top"></button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>