<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation">
        <div class="row">
            <ul id="parallelogram2">
            </ul>
            <ul id="parallelogram">
            </ul>
        </div>
        <ul class="menu rojo">
            <li class="first expanded">
				<span class="active main">
					<p class="letraMenu">CONFERENCIAS <br> MAGISTRALES</p>
				</span>
            </li>
        </ul>
    </div>
</div>
<div id="main">
    <section class="cp-blog padding-top-60">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="cp-post-box">
                        <div class="frame cp-img-effect-1 diplomado">
                            <a href="#"><img src="/front/src/images/blog/blog-img-55.jpg" alt="img"></a>
                        </div>
                        <div class="cp-text-box">
                            <h5>LISTADO DE CONFERENCIAS</h5>
                            <p class="text-justify">Los participantes contarán con una formación especializada que comprenda los elementos teórico-conceptuales, los mecanismos prácticos y las herramientas metodológicas a través del planteamiento de nuevos enfoques y el análisis multidisciplinario, a fin de proponer alternativas en la promoción y defensa de los Derechos Humanos.</p>
                            <h5>Objetivos específicos</h5>
                            <p class="text-justify">Proporcionar a los participantes:
                                <br>
                                a) Herramientas analíticas de carácter interpretativo que permitan un adecuado conocimiento en el tema de derechos humanos.
                                <br>
                                b) Instrumentos para la aplicación práctica de los procedimientos de casos concretos con una implementación de todas las herramientas conceptuales adquiridas que permitan la materialización de los contenidos teóricos abordados.
                            </p>
                            <h5>MÓDULOS QUE CONFORMAN EL DIPLOMADO</h5>
                            <ul>
                                <li>Módulo I. Los Derechos Humanos en el Contexto Internacional</li>
                                <li>Módulo II. Principio Pro Persona</li>
                                <li>Módulo III. Bloque Integral de Constitucionalidad</li>
                                <li>Módulo IV. Interpretación Conforme</li>
                                <li>Módulo V. Control Difuso de Constitucionalidad y Convencionalidad</li>
                                <li>Módulo VI. Principios y Obligaciones de los Derechos Humanos</li>
                                <li>Módulo VII. Los Deberes Específicos de los Derechos Humanos</li>
                                <li>Módulo VIII. Teoría de las Reparaciones de los Derechos Humanos</li>
                                <li>Módulo IX. Instituciones de Protección de los Derechos Humanos</li>
                                <li>Módulo IX. Los Derechos Humanos a Grupos en Situación de Vulnerabilidad</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>