<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
	<div class="content main-navigation">
		<div class="row">
			<div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
				<ul id="parallelogram">
				</ul>
			</div>
			<div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
				<p class="titleview"><?=$subcategory->subcategoryname; ?></p>
			</div>
			<div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
				<ul id="parallelogram2">
				</ul>
			</div>
		</div>

	</div>
</div>
<div id="main">
	<section class="cp-blog padding-top-60">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cp-post-box">
						<div class="frame cp-img-effect-1 diplomado">
							<a href="#"><img src="/dash/img/notes/<?=$curso->image;?>" alt="img"></a>
						</div>
						<div class="cp-text-box">
							<h2><?=$curso->title;?></h2>
							<?=$curso->content;?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>