<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
	<div class="content main-navigation a">
		<ul class="menu rojo">
			<li class="first expanded">
				<img class="menuFondo" src="/front/src/images/menu.png" alt=""/>
				  <span class="active main">
					<p class="letraMenu">DIPLOMADO EN DERECHO ELECTORAL<br> Y DERECHO PROCESAL ELECTORAL</p>
				  </span>
			</li>
		</ul>
	</div>
</div>
<div id="main">
	<section class="cp-blog padding-top-60">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cp-post-box">
						<div class="frame cp-img-effect-1 diplomado">
							<a href="#"><img src="/front/src/images/blog/blog-img-555.jpg" alt="img"></a>
						</div>
						<div class="cp-text-box">
							<h5>Objetivo general</h5>
							<p class="text-justify">Los participantes tendrán el conocimiento fundamental de la democracia y del sistema electoral para desarrollar estrategias, analizando cada una de las etapas del proceso electoral y sistema de nulidades, a través de los diversos medios de impugnación.</p>
							<h5>Objetivos específicos</h5>
							<p class="text-justify">Proporcionar a los participantes:
							<br>
							a) Herramientas analíticas de carácter interpretativo que permitan un adecuado conocimiento del tema electoral.
							<br>
							b) Instrumentos para la aplicación práctica de los recursos, juicios y procedimientos administradores de casos concretos con una implementación de todas las herramientas conceptuales adquiridas que permitan la materialización de los contenidos teóricos abordados.
							</p>
							<h5>MÓDULOS QUE CONFORMAN EL DIPLOMADO</h5>
							<ul>
								<li>Módulo 1. Conceptos fundamentales de derecho y ciencia política</li>
								<li>Módulo 2. Conceptos fundamentales de derecho procesal y derecho probatorio</li>
								<li>Módulo 3. La argumentación jurídica y sus implicaciones prácticas</li>
								<li>Módulo 4. El proceso electoral y sus etapas</li>
								<li>Módulo 5. La comunicación política y estrategias en campañas electorales</li>
								<li>Módulo 6. El sistema de nulidades en materia electoral y sus medios de impugnación</li>
								<li>Módulo 7. Los procedimientos administrativos sancionadores en materia electoral</li>
								<li>Módulo 8. Derecho penal electoral.</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>