<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
    <div class="content main-navigation a">
        <ul class="menu rojo">
            <li class="first expanded">
                <img class="menuFondo" src="/front/src/images/menu.png" alt=""/>
				  <span class="active main">
					<a class="letraMenu">DIPLOMADO EN INTERPRETACIÓN <br>Y ARGUMENTACIÓN JURÍDICA</a>
				  </span>
            </li>
        </ul>
    </div>
</div>
<div id="main">
    <section class="cp-blog padding-top-60">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="cp-post-box">
                        <div class="frame cp-img-effect-1">
                            <a href="#"><img src="/front/src/images/blog/blog-img-5.jpg" alt="img"></a>
                        </div>
                        <div class="cp-text-box">
                            <h5>Objetivo general</h5>
                            <p class="text-justify">Los participantes contarán con una formación especializada que comprenda los elementos teórico-conceptuales, los mecanismos prácticos y las herramientas metodológicas a través del planteamiento de nuevos enfoques y el análisis multidisciplinario, a fin de que conozcan los aspectos generales, los criterios y los procedimientos de la interpretación y la argumentación jurídica, a través una adecuada argumentación y una correcta interpretación de las normas jurídicas.</p>
                            <h5>Objetivos específicos</h5>
                            <p class="text-justify">Proporcionar a los participantes:
                                <br>
                                a) Herramientas analíticas de carácter interpretativo que permitan un adecuado conocimiento en el tema de interpretación y argumentación jurídica.
                                <br>
                                b) Instrumentos para la aplicación práctica de los procedimientos de casos concretos con una implementación de todas las herramientas conceptuales.
                            </p>
                            <h5>MÓDULOS QUE CONFORMAN EL DIPLOMADO</h5>
                            <ul>
                                <li>Módulo I. Lenguaje jurídico y derecho</li>
                                <li>Módulo II. Lógica Jurídica</li>
                                <li>Módulo III. La interpretación del derecho</li>
                                <li>Módulo IV. La ley como objeto de interpretación</li>
                                <li>Módulo V. Teorías de la interpretación jurídica</li>
                                <li>Módulo VI. Argumentos interpretativos</li>
                                <li>Módulo VII. El derecho como argumentación jurídica</li>
                                <li>Módulo VIII. Teorías de la argumentación jurídica</li>
                                <li>Módulo IX. Argumentación en materia de hechos.</li>
                                <li>Módulo X. Taller de interpretación y argumentación jurídica.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>