<div id="block-drupalnav-drupalnav" class="block block-drupalnav">
	<div class="content main-navigation">
		<div class="row">
			<div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
				<ul id="parallelogram">
				</ul>
			</div>
			<div class="col-sm2 col-md-2 col-lg-2 col-xs-4">
				<p class="titleview">Investigadores</p>
			</div>
			<div class="col-sm5 col-md-5 col-lg-5 col-xs-4">
				<ul id="parallelogram2">
				</ul>
			</div>
		</div>

	</div>
</div>
<section class="cp-attorneys-team cp-attorneys-team-space-2 padding-top-60 investigadores">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<ul class="pgwSlideshow">
					<?php foreach($inves as $value):?>
					<li>
						<img class="investigadores" src="/front/src/images/attorneys/263x320/<?=$value->photo?>" alt="<?=$value->name?> <?=$value->lastname?>" data-description="<?=$value->description?>">
					</li>
					<?php endforeach;?>
				</ul>
			</div>
		</div>
	</div>
</section>
