<!DOCTYPE html>
<html>
<head>
    <?php $meta= $this->session->get("meta");?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $meta['title']?></title>
    <meta name="description" content="<?= $meta['description']?>" />
    <meta name="revisit-after" content="7 days">
    <meta name="googlebot" content="follow, index, all">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Proceso electoral en mexico, campañas electorales en mexico, partidos politicos en mexico,
    jornada electoral en mexico, elecciones en mexico, sistema de medios de impugnación en mexico, encuestas electorales en mexico,
    marketing electoral  en mexico, comunicación politica en mexico" />
    <meta name="author" content="www.c-developers.com" />
    <meta name="copyright" content="2016 C-Developers Todos los derechos reservados." />
    <meta name="application-name" content="IIDE" />
    <link rel="canonical" href="<?= $meta['url']?>" />
    <meta name="robots" content="follow, index">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="or01GUAHUBMCMqUDL85g00YbakjP1Mbp9Px-6Q2BW6g" />
    <!-- Cache Control  -->
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <!--Meta Facebook -->
    <meta property="og:title" content="<?= $meta['title']?>"/>
    <meta property="og:type" content="website" />
    <meta property="og:image" content="">
    <meta property="og:url" content="<?= $meta['url']?>"/>
    <meta property="og:description" content="<?= $meta['description']?>"/>
    <meta property="og:site_name" content="<?= $meta['url']?>"/>
    <!--Twitter-->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="<?= $meta['title']?>" />
    <meta name="twitter:description" content="<?= $meta['description']?>" />
    <meta name="twitter:image" content="" />
    <meta property="og:image:width" content="800" />
    <meta property="og:image:height" content="600" />
    <?= $this->assets->outputCss("FrontEndCss")?>

    <?php
    $plugins = $this->assets->collection('jsPlugins');
    if (!empty($plugins)) {echo $this->assets->outputJs('jsPlugins');}
    ?>
    <link href="/front/src/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="icon" href="/front/src/images/iconoIIDE.png" type="image/png">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="/front/src/js/jquery-1.11.3.min.js"></script>
</head>

<body class="cp-theme-style-1">
<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.9";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div id="wrapper">
    <header id="header">
        <section class="cp-head-topbar visible-md visible-lg">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-xs-12">
                        <div class="left-box">
                            <ul class="header">
                                <li>Teléfono: <a href="#" class="header-phone">55 60 62 77 22</a></li>
                                <li>Email: <a href="mailto:" class="header-email"><span class="__cf_email__">contactanos@iide.com.mx</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12">
                        <div class="right-box">
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <section class="cp-navigation-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-xs-12 col-sm-12">
                        <strong class="logo visible-md visible-lg">
                            <a href="/">
                                <img src="/front/src/images/logo-iide.png" alt="Proceso electoral en mexico" style="width: 100%;">
                            </a>
                        </strong>
                        <strong class="logo visible-sm">
                            <a href="/">
                                <img src="/front/src/images/logo-iide.png" alt="campañas electorales el mexico">
                            </a>
                        </strong>
                        <div class="navigation-right">
                            <nav class="navbar navbar-inverse">
                                <div class="navbar-header">
                                    <strong class="logo visible-xs">
                                        <a href="/">
                                            <img src="/front/src/images/logo-iide.png" alt="partidos politicos en mexico">
                                        </a>
                                    </strong>
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                            data-target="#navbar" aria-expanded="false" aria-controls="navbar"><span
                                            class="sr-only">IBEDEL</span> <span class="icon-bar"></span> <span
                                            class="icon-bar"></span> <span class="icon-bar"></span></button>
                                </div>
                                <div id="navbar" class="collapse navbar-collapse">
                                    <ul id="nav" class="navbar-nav">

                                        <li class="active menumovil hidden-xs"><a class="salamanca" href="/"><i class="fa fa-home inicio" aria-hidden="true"></i></a></li>
                                        <li class="active menumovil"><a class="salamanca" href="/quienes-somos">IIED</a></li>
                                        <li class="menumovil"><a class="salamanca" href="/oferta-de-estudio">Estudia en el IIED</a>
                                            <!--ul>
                                                <li><a class="salamanca" href="/quienes-somos">Quiénes somos</a></li>
                                                <li><a class="salamanca" href="/forma-de-trabajo">Forma de trabajo</a></li>
                                            </ul-->
                                        </li>
                                        <li class="menumovil"><a class="salamanca" href="/investigadores">Investigadores</a></li>
                                        <li class="menumovil"><a class="salamanca" href="/sistema-electoral-iberoamericano"><p class="menu">Sistema Electoral</p>
                                                <p class="menu"> Iberoamericano</p></a></li>
                                        <li class="menumovil"><a class="salamanca" href="/iberonautas">Iberonautas</a></li>
                                        <li class="menumovil"><a class="salamanca" href="/revista">Revista IIDE</a></li>
                                        <li class="menumovil"><a class="salamanca" href="/directorio">Directorio</a></li>
                                        <li class="menumovil"><a class="salamanca" href="/contactanos">Contáctanos</a></li>
                                    </ul>
                                </div>
                            </nav>
                            <!--input title="Escriba lo que quiere buscar." placeholder="Buscar" type="text" id="edit-search-block-form--2" name="search_block_form" value="" size="15" maxlength="128" class="form-text form-control">
                            <br-->
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </header>
    <?= $this->getContent();?>

    <footer id="footer">
        <section class="cp-footer-content">
            <div class="container">
                <div class="row">
                    <div class="cp-copyright-section1">
                        <div class="col-md-5 col-sm-5 col-xs-12 hidden-xs">
                            <ul class="footer-social1">
                                <li>
                                    <p class="text" href="/contactanos">Contacta con IIDE</p>
                                </li>
                                <li>
                                    <a href="https://www.facebook.com/IIDEMEXICO1/"  target="_blank"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/IIDE_MEXICO?ref_src=twsrc%5Etfw&ref_url=http%3A%2F%2Flocal.ibedel.com%2F"  target="_blank"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="https://www.youtube.com/channel/UCTnp0ayG_BhWUjXo-Q1h_Xw"  target="_blank"><i class="fa fa-youtube"></i></a>
                                </li>
                                <li>
                                    <p class="text sitiointeres" href="#">Sitio de Interes</p>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-12">
                            <!--div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:1180px;height:100px;overflow:hidden;visibility:hidden;">
                                <div data-u="loading" style="position:absolute;top:0px;left:0px;background:url('img/loading.gif') no-repeat 50% 50%;background-color:rgba(0, 0, 0, 0.7);"></div>
                                <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:1180px;height:100px;overflow:hidden;">
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-9.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-10.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-12.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-6.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-11.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-13.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-14.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-15.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-16.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-17.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-18.png" />
                                    </div>




                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-19.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-20.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-21.png" />
                                    </div>
                                    <div>
                                        <img data-u="image" src="/front/src/images/client/client-img-22.png" />
                                    </div>

                                    <a data-u="any" href="https://www.jssor.com" style="display:none">js slider</a>
                                </div>
                            </div-->
                            <div id="myCarousel3" class="carousel slide col-md-12 col-xs-12 col-sm-12" data-ride="carousel">
                                <ol class="carousel-indicators footer">
                                    <li data-target="#myCarousel3" data-slide-to="0" class="active"></li>
                                    <li data-target="#myCarousel3" data-slide-to="1"></li>
                                    <li data-target="#myCarousel3" data-slide-to="2"></li>
                                    <li data-target="#myCarousel3" data-slide-to="3"></li>
                                </ol>
                                <div class="carousel-inner">
                                    <div class="item active">
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="http://www.senado.gob.mx/index.php" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-9.png" alt="jornada electoral en mexico"></a>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="http://www.diputados.gob.mx/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-10.png" alt="Proceso electoral en mexico"></a>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="https://www.scjn.gob.mx/Paginas/Inicio.aspx" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-12.png" alt="Proceso electoral en mexico"></a>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="http://www.ine.mx/portal/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-6.png" alt="Proceso electoral en mexico"></a>
                                            </div>
                                    </div>
                                    <div class="item">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.trife.gob.mx/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-11.png" alt="Proceso electoral en mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="/oples" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-13.png" alt="Proceso electoral en mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="/tribunales" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-14.png" alt="Proceso electoral en mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.oas.org/es/cidh/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-15.png" alt="Proceso electoral en mexico"></a>
                                        </div>
                                    </div>

                                    <div class="item">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.echr.coe.int/Pages/home.aspx?p=home" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-16.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://curia.europa.eu/jcms/jcms/j_6/es/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-17.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.un.org/es/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-18.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.corteidh.or.cr/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-19.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.icj-cij.org/homepage/sp/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-20.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://es.unesco.org/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-21.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.undp.org/es/" target="_blank"><img class="sitiosInteres" src="/front/src/images/client/client-img-22.png" alt="campañas electorales el mexico"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </footer>
</div>
<!--div id="copyright-container">
    <a href="#" class="scroll-up"><i class="fa fa-angle-double-up"></i></a>
</div-->
<?php
$plugins = $this->assets->collection('jsPlugins2');
if (!empty($plugins)) {echo $this->assets->outputJs('jsPlugins2');}
echo $this->assets->outputJs('FrontEndJs');
?>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBXJhvw6cSlDXrS_iNYtBpO_F1egYc4lEw"></script>
<script>
    jQuery(document).ready(function($) {
        $('.my-slider2').unslider({

            infinite: true,
            autoplay: true,
            delay: 10000,
            arrows: false

        });
    });
</script>
<script type="text/javascript">/* <![CDATA[ */
    (function (d, s, a, i, j, r, l, m, t) {
        try {
            l = d.getElementsByTagName('a');
            t = d.createElement('textarea');
            for (i = 0; l.length - i; i++) {
                try {
                    a = l[i].href;
                    s = a.indexOf('/cdn-cgi/l/email-protection');
                    m = a.length;
                    if (a && s > -1 && m > 28) {
                        j = 28 + s;
                        s = '';
                        if (j < m) {
                            r = '0x' + a.substr(j, 2) | 0;
                            for (j += 2; j < m && a.charAt(j) != 'X'; j += 2)s += '%' + ('0' + ('0x' + a.substr(j, 2) ^ r).toString(16)).slice(-2);
                            j++;
                            s = decodeURIComponent(s) + a.substr(j, m - j)
                        }
                        t.innerHTML = s.replace(/</g, '&lt;').replace(/>/g, '&gt;');
                        l[i].href = 'mailto:' + t.value
                    }
                } catch (e) {
                }
            }
        } catch (e) {
        }
    })(document);
    /* ]]> */</script>
    <?php if ($this->router->getActionName() == 'viewrevista') { ?>
      <?php echo $this->assets->outputJs('MagazineJs'); ?>
        <script type="text/javascript">

    function toggleFullScreen(elem) {
        // ## The below if statement seems to work better ## if ((document.fullScreenElement && document.fullScreenElement !== null) || (document.msfullscreenElement && document.msfullscreenElement !== null) || (!document.mozFullScreen && !document.webkitIsFullScreen)) {
        if ((document.fullScreenElement !== undefined && document.fullScreenElement === null) || (document.msFullscreenElement !== undefined && document.msFullscreenElement === null) || (document.mozFullScreen !== undefined && !document.mozFullScreen) || (document.webkitIsFullScreen !== undefined && !document.webkitIsFullScreen)) {
            if (elem.requestFullScreen) {
                elem.requestFullScreen();
            } else if (elem.mozRequestFullScreen) {
                elem.mozRequestFullScreen();
            } else if (elem.webkitRequestFullScreen) {
                elem.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
            } else if (elem.msRequestFullscreen) {
                elem.msRequestFullscreen();
            }else{
                var wscript = new ActiveXObject("Wscript.shell");
                wscript.SendKeys("{F11}");
            }
        } else {
            if (document.cancelFullScreen) {
                document.cancelFullScreen();
            } else if (document.mozCancelFullScreen) {
                document.mozCancelFullScreen();
            } else if (document.webkitCancelFullScreen) {
                document.webkitCancelFullScreen();
            } else if (document.msExitFullscreen) {
                document.msExitFullscreen();
            }
        }
    }
    function loadApp() {
        $('#canvas').fadeIn(1000);
        var flipbook = $('.magazine');
        // Check if the CSS was already loaded
        if (flipbook.width()==0 || flipbook.height()==0) {
            setTimeout(loadApp, 10);
            return;
        }
        // Create the flipbook
        flipbook.turn({
            // Magazine width
            width: 922,
            // Magazine height
            height: 600,
            // Duration in millisecond
            duration: 1000,
            // Enables gradients
            gradients: true,
            // Auto center this flipbook
            autoCenter: true,
            // Elevation from the edge of the flipbook when turning a page
            elevation: 48,
            // The number of pages
            pages: 32,
            // Events
            when: {
                turning: function(event, page, view) {
                    var book = $(this),
                        currentPage = book.turn('page'),
                        pages = book.turn('pages');
                    // Update the current URI
                    Hash.go('page/' + page).update();
                    // Show and hide navigation buttons
                    disableControls(page);
                },
                turned: function(event, page, view) {
                    disableControls(page);
                    $(this).turn('center');
                    $('#slider').slider('value', getViewNumber($(this), page));
                    if (page==1) {
                        $(this).turn('peel', 'br');
                    }
                },
                missing: function (event, pages) {
                    // Add pages that aren't in the magazine
                    for (var i = 0; i < pages.length; i++)
                        addPage(pages[i], $(this));
                }
            }
        });
        // Zoom.js
        $('.magazine-viewport').zoom({
            flipbook: $('.magazine'),
            max: function() {
                return largeMagazineWidth()/$('.magazine').width();
            },
            when: {
                swipeLeft: function() {
                    $(this).zoom('flipbook').turn('next');
                },
                swipeRight: function() {
                    $(this).zoom('flipbook').turn('previous');
                },
                resize: function(event, scale, page, pageElement) {
                    if (scale==1)
                        loadSmallPage(page, pageElement);
                    else
                        loadLargePage(page, pageElement);
                },
                zoomIn: function () {
                    $('#slider-bar').hide();
                    $('.made').hide();
                    $('.magazine').removeClass('animated').addClass('zoom-in');
                    $('.zoom-icon').removeClass('zoom-icon-in').addClass('zoom-icon-out');
                    if (!window.escTip && !$.isTouch) {
                        escTip = true;
                        $('<div />', {'class': 'exit-message'}).
                            html('<div>Presiona ESC para salir</div>').
                            appendTo($('body')).
                            delay(2000).
                            animate({opacity:0}, 500, function() {
                                $(this).remove();
                            });
                    }
                },
                zoomOut: function () {
                    $('#slider-bar').fadeIn();
                    $('.exit-message').hide();
                    $('.made').fadeIn();
                    $('.zoom-icon').removeClass('zoom-icon-out').addClass('zoom-icon-in fa fa-search-plus');
                    setTimeout(function(){
                        $('.magazine').addClass('animated').removeClass('zoom-in');
                        resizeViewport();
                    }, 0);
                }
            }
        });
        // Zoom event
        if ($.isTouch)
            $('.magazine-viewport').bind('zoom.doubleTap', zoomTo);
        else
            $('.magazine-viewport').bind('zoom.tap', zoomTo);
        // Using arrow keys to turn the page
        $(document).keydown(function(e){
            var previous = 37, next = 39, esc = 27;
            switch (e.keyCode) {
                case previous:
                    // left arrow
                    $('.magazine').turn('previous');
                    e.preventDefault();
                    break;
                case next:
                    //right arrow
                    $('.magazine').turn('next');
                    e.preventDefault();
                    break;
                case esc:
                    $('.magazine-viewport').zoom('zoomOut');
                    e.preventDefault();
                    break;
            }
        });
        // URIs - Format #/page/1
        Hash.on('^page\/([0-9]*)$', {
            yep: function(path, parts) {
                var page = parts[1];
                if (page!==undefined) {
                    if ($('.magazine').turn('is'))
                        $('.magazine').turn('page', page);
                }
            },
            nop: function(path) {
                if ($('.magazine').turn('is'))
                    $('.magazine').turn('page', 1);
            }
        });
        $(window).resize(function() {
            resizeViewport();
        }).bind('orientationchange', function() {
            resizeViewport();
        });
        // Regions
        if ($.isTouch) {
            $('.magazine').bind('touchstart', regionClick);
        } else {
            $('.magazine').click(regionClick);
        }
        // Events for the next button
        $('.next-button').bind($.mouseEvents.over, function() {
            $(this).addClass('next-button-hover');
        }).bind($.mouseEvents.out, function() {
            $(this).removeClass('next-button-hover');
        }).bind($.mouseEvents.down, function() {
            $(this).addClass('next-button-down');
        }).bind($.mouseEvents.up, function() {
            $(this).removeClass('next-button-down');
        }).click(function() {
            $('.magazine').turn('next');
        });
        // Events for the next button
        $('.previous-button').bind($.mouseEvents.over, function() {
            $(this).addClass('previous-button-hover');
        }).bind($.mouseEvents.out, function() {
            $(this).removeClass('previous-button-hover');
        }).bind($.mouseEvents.down, function() {
            $(this).addClass('previous-button-down');
        }).bind($.mouseEvents.up, function() {
            $(this).removeClass('previous-button-down');
        }).click(function() {
            $('.magazine').turn('previous')
        });
        // Slider
        $( "#slider" ).slider({
            min: 1,
            max: numberOfViews(flipbook),
            start: function(event, ui) {
                if (!window._thumbPreview) {
                    _thumbPreview = $('<div />', {'class': 'thumbnail'}).html('<div></div>');
                    setPreview(ui.value);
                    _thumbPreview.appendTo($(ui.handle));
                } else
                    setPreview(ui.value);
                moveBar(false);
            },
            slide: function(event, ui) {
                setPreview(ui.value);
            },
            stop: function() {
                if (window._thumbPreview)
                    _thumbPreview.removeClass('show');
                $('.magazine').turn('page', Math.max(1, $(this).slider('value')*2 - 2));
            }
        });
        resizeViewport();
        $('.magazine').addClass('animated');
    }
    // Zoom icon
    $('.zoom-icon').bind('mouseover', function() {
        if ($(this).hasClass('zoom-icon-in'))
            $(this).addClass('zoom-icon-in-hover');
        if ($(this).hasClass('zoom-icon-out'))
            $(this).addClass('zoom-icon-out-hover');
    }).bind('mouseout', function() {
        if ($(this).hasClass('zoom-icon-in'))
            $(this).removeClass('zoom-icon-in-hover');
        if ($(this).hasClass('zoom-icon-out'))
            $(this).removeClass('zoom-icon-out-hover');
    }).bind('click', function() {
        if ($(this).hasClass('zoom-icon-in'))
            $('.magazine-viewport').zoom('zoomIn');
        else if ($(this).hasClass('zoom-icon-out'))
            $('.magazine-viewport').zoom('zoomOut');
    });
    $('#canvas').hide();
    // Load the HTML4 version if there's not CSS transform
    yepnope({
        test : Modernizr.csstransforms,
        yep: ['/front/assets/js/magazing/turn.min.js'],
        nope: ['/front/assets/js/magazing/turn.html4.min.js', '/front/assets/css/magazing/jquery.ui.html4.css'],
        both: ['/front/assets/js/magazing/zoom.min.js', '/front/assets/css/magazing/jquery.ui.css', '/front/assets/js/magazing/magazine.js', '/front/assets/css/magazing/magazine.css'],
        complete: loadApp
    });
    </script>

    <?php } ?>
<script id="dsq-count-scr" src="//http-iide-com-mx.disqus.com/count.js" async></script>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58b7201ade0139f3"></script>
</body>
</html>